# Site settings
title: 'Chen Yanlong'
description: '我希望活得深刻,汲取生命所有的精髓! 把非生命的一切全都击溃<br/>以免在我生命终结时,发现自己从来没有活过'
url: ''
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Chen Yanlong'
  email: 15636039213@163.com
  github_username:  CYanLong
  linkedin_username:  艳龙-陈-847441118

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: pretty
markdown: kramdown
highlighter: 

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
